### ISSUE TITLE
Peculiar behavior while importing Apify Datasets

### ISSUE THREAD

**Issue by Zyberg** [metalwarrior665/actor-google-sheets#19]
Not too sure what is going on, but when I am importing my custom Dataset, sometimes the columns with numbers output a different number than given (as in: spreadsheet contains one number, Dataset a whole another number).

Can't really share the Dataset due to my client's privacy reasons, but the particular value is 1,24. It gets converted to 43854. Also, it seems that some other numeric values are disbehaving as well.

Since it is monetary data, differences even of a small magnitude have a huge impact.

I am not using any transform function, just `deduplicate by equality`. I've got the columns custom ordered, if that could make any difference.

I am going to try to debug the code myself, but any help / insight would be wonderful.

**Comment by metalwarrior665** [comment]
Hello,

I'm sorry that I missed this issue completely. I don't see how `1,24` could automatically transform into `43854`. Don't you have some functions there? About half a year, I did a change so that numeric values are parsed into numbers in the sheets but that should behave as you expect.

Would you be able to reproduce this bug on a sample dataset? You can use `rawData` for that.

**Comment by Zyberg** [comment]
Hello! I ended up abandoning your actor as I needed the solution asap, but tinkering with input now I see that when google sheet interprets incoming number as date, after setting whole column to number type it becomes some huge number (probably unix timestamp seconds or whatever).
So, the problem is probably with making google sheets parse all numbers as numbers.


**SOLVED**: I can confirm that the problem was in me storing floating point data as strings. In my case it has little use and is simple to transform the data, but this should be put somewhere visible for other users of this actor :) In case anybody else stumbles upon this weird glitch use this tranform function within the actor on your string property (edit it accordingly) : 
```
function transform({ datasetData, spreadsheetData }) {
    return datasetData
        .map(i => ({...i, 'FloatingNumber': parseFloat(i.FloatingNumber)}))
        .map(i => ({...i, 'FloatingNumber': i.FloatingNumber ? i.FloatingNumber : '0'}))
}
```

**NOTE** I still needed to change the column format explicitly to number for google sheets to display data as a number, not a date, when possible. Not sure, if this can be automated yet, but will look into it.
Failing row column was:
```
{
    FloatingNumber: "1.11"
}
```

**Comment by Zyberg** [comment]
Also, probably would be great to edit input editor info so that transform function has parameter names or an example declaration. Had to look up source code to find the info :)

**Comment by Zyberg** [comment]
**Quick note, might need somebody to confirm this:** saving floating point numbers as strings where floating point is denoted by comma (`,`) instead of a dot (`.`) doesn't require any modification and the field is automatically regarded as numeric.
However, tested only on a machine with locale where floating point is usually delimited by comma and since I've got no idea how to change that on google sheets, can't test if it works for other locales similarly.

**Comment by metalwarrior665** [comment]
Thanks a lot for looking into this. I guess there is not that much I can do about it as the import is using the default Google Sheets parser which should work as if you input the values manually. For me, if I send a string to my sheet, dot works as a number but comma does not so it might be because of localization. So I will add some note to the readme that users need to be aware of this.

Actually, on Apify, if you create a new task, the transform function should have commented example declaration.

Before I wasn't using the parser at all but then all values were just string so no one could do calculations and it was terrible.
