### ISSUE TITLE
Apify Webhooks Not Working

### ISSUE THREAD

**Issue by KarlPiper** [metalwarrior665/actor-google-sheets#8]
I am trying to connect [Web-Scraper](https://apify.com/apify/web-scraper) to Google-Sheets using but can't get it to work.

Does Google-Sheets support use of Apify's built-in Webhooks feature, instead of the "Finish Webhook Data" field referenced in the docs? Only the Legacy Crawler has that field.

When I try, this is the error I get `Error: WRONG INPUT! - datasetOrExecutionId field needs to be a string with 17 characters!`

I could convert to using the Legacy Crawler but it doesn't support ES6. Any help would be great.

**Comment by metalwarrior665** [comment]
Hi Karl,

Sorry that I noticed your issue so late. The new version of this actor now supports only the built-in webhooks. It is explained in the README.

This error that you get is because there was a breaking change in the input. You have to rename
```datasetOrExecutionId ```
to
```datasetId```

I'm sorry, this wasn't meant to be forced to old users but Apify system did not allow versioned updates. This feature is now available.

**Comment by KarlPiper** [comment]
Thank you!
